[2025-11-01T17:43:34.002+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T17:43:28.391037+00:00 [queued]>
[2025-11-01T17:43:34.039+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T17:43:28.391037+00:00 [queued]>
[2025-11-01T17:43:34.040+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-11-01T17:43:34.121+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_csv_to_clickhouse> on 2025-11-01 17:43:28.391037+00:00
[2025-11-01T17:43:34.172+0000] {standard_task_runner.py:60} INFO - Started process 232 to run task
[2025-11-01T17:43:34.207+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'load_csv_to_clickhouse', 'load_csv_to_clickhouse', 'manual__2025-11-01T17:43:28.391037+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/load_to_clickhouse.py', '--cfg-path', '/tmp/tmpf_l_gvn5']
[2025-11-01T17:43:34.341+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask load_csv_to_clickhouse
[2025-11-01T17:43:35.497+0000] {task_command.py:423} INFO - Running <TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T17:43:28.391037+00:00 [running]> on host 5fa557a7832a
[2025-11-01T17:43:50.400+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_csv_to_clickhouse' AIRFLOW_CTX_TASK_ID='load_csv_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T17:43:28.391037+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T17:43:28.391037+00:00'
[2025-11-01T17:43:55.128+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/load_to_clickhouse.py:31 UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
[2025-11-01T17:43:55.306+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/load_to_clickhouse.py:31 UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
[2025-11-01T17:43:58.331+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_to_clickhouse.py", line 56, in load_csv_to_clickhouse
    client.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 376, in execute
    rv = self.process_insert_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 607, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 660, in send_data
    self.connection.send_data(block)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 688, in send_data
    self.block_out.write(block)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/streams/native.py", line 48, in write
    write_column(self.context, col_name, col_type, items,
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/columns/service.py", line 167, in write_column
    column.write_data(items, buf)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/columns/base.py", line 145, in write_data
    self._write_data(items, buf)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/columns/base.py", line 148, in _write_data
    prepared = self.prepare_items(items)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/columns/base.py", line 137, in prepare_items
    self.before_write_items(items, nulls_map=nulls_map)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/columns/datecolumn.py", line 84, in before_write_items
    item = date(item.year, item.month, item.day)
TypeError: integer argument expected, got float
[2025-11-01T17:43:58.430+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=load_csv_to_clickhouse, task_id=load_csv_to_clickhouse, execution_date=20251101T174328, start_date=20251101T174334, end_date=20251101T174358
[2025-11-01T17:43:58.482+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 28 for task load_csv_to_clickhouse (integer argument expected, got float; 232)
[2025-11-01T17:43:58.551+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T17:43:58.654+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
